[project]
name = "simple-agent-poc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "litellm>=1.81.14",
    "python-dotenv>=1.2.1",
]

[project.scripts]
dev = "simple_agent_poc.main:main"

[tool.uv]
package = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ruff>=0.15.2",
]

[tool.hatch.build.targets.wheel]
packages = ["src/simple_agent_poc"]
